"""
Agent models - Tracks AI agent interactions and tasks
"""

from django.db import models
from django.conf import settings
from foiamachine.apps.core.models import TimeStampedModel


class AgentTask(TimeStampedModel):
    """
    Represents a task that an AI agent performs or has performed
    """
    TASK_TYPE_CHOICES = [
        ('draft_request', 'Draft FOIA Request'),
        ('analyze_response', 'Analyze Response'),
        ('generate_followup', 'Generate Follow-up'),
        ('summarize_document', 'Summarize Document'),
        ('suggest_improvements', 'Suggest Improvements'),
        ('prioritize_tasks', 'Prioritize Tasks'),
    ]
    
    STATUS_CHOICES = [
        ('pending', 'Pending'),
        ('processing', 'Processing'),
        ('completed', 'Completed'),
        ('failed', 'Failed'),
    ]
    
    task_type = models.CharField(max_length=30, choices=TASK_TYPE_CHOICES)
    status = models.CharField(max_length=20, choices=STATUS_CHOICES, default='pending')
    
    # User who initiated the task
    user = models.ForeignKey(
        settings.AUTH_USER_MODEL,
        on_delete=models.CASCADE,
        related_name='agent_tasks'
    )
    
    # Optional: Related FOIA request
    foia_request = models.ForeignKey(
        'requests.FOIARequest',
        on_delete=models.CASCADE,
        null=True,
        blank=True,
        related_name='agent_tasks'
    )
    
    # Input and output
    input_data = models.JSONField(
        help_text="Input data provided to the agent"
    )
    output_data = models.JSONField(
        null=True,
        blank=True,
        help_text="Output generated by the agent"
    )
    
    # Processing details
    started_at = models.DateTimeField(null=True, blank=True)
    completed_at = models.DateTimeField(null=True, blank=True)
    error_message = models.TextField(blank=True)
    
    # Agent metadata
    agent_model = models.CharField(max_length=100, default='gpt-4-turbo-preview')
    tokens_used = models.IntegerField(default=0)
    
    class Meta:
        ordering = ['-created_at']
        verbose_name = 'Agent Task'
        verbose_name_plural = 'Agent Tasks'
    
    def __str__(self):
        return f"{self.get_task_type_display()} - {self.get_status_display()}"


class AgentSuggestion(TimeStampedModel):
    """
    Stores suggestions made by AI agents
    """
    user = models.ForeignKey(
        settings.AUTH_USER_MODEL,
        on_delete=models.CASCADE,
        related_name='agent_suggestions'
    )
    
    foia_request = models.ForeignKey(
        'requests.FOIARequest',
        on_delete=models.CASCADE,
        related_name='agent_suggestions'
    )
    
    suggestion_type = models.CharField(max_length=50)
    title = models.CharField(max_length=500)
    description = models.TextField()
    
    # Suggested changes or actions
    suggested_text = models.TextField(
        blank=True,
        help_text="Suggested text or content"
    )
    
    # User actions
    is_accepted = models.BooleanField(default=False)
    is_rejected = models.BooleanField(default=False)
    feedback = models.TextField(
        blank=True,
        help_text="User feedback on the suggestion"
    )
    
    class Meta:
        ordering = ['-created_at']
    
    def __str__(self):
        return f"{self.title} - {self.foia_request.title[:50]}"


class AgentWorkflow(TimeStampedModel):
    """
    Defines automated workflows that agents can execute
    """
    name = models.CharField(max_length=200)
    description = models.TextField()
    
    # Workflow configuration
    trigger_event = models.CharField(
        max_length=50,
        help_text="Event that triggers this workflow (e.g., 'request_submitted')"
    )
    
    actions = models.JSONField(
        help_text="List of actions the agent should perform"
    )
    
    is_active = models.BooleanField(default=True)
    
    # Usage statistics
    execution_count = models.IntegerField(default=0)
    success_count = models.IntegerField(default=0)
    failure_count = models.IntegerField(default=0)
    
    class Meta:
        ordering = ['name']
    
    def __str__(self):
        return self.name
