"""
FOIA Request models
"""

from django.db import models
from django.conf import settings
from foiamachine.apps.core.models import TimeStampedModel, SoftDeleteModel


class FOIARequest(TimeStampedModel, SoftDeleteModel):
    """
    Represents a FOIA request
    """
    STATUS_CHOICES = [
        ('draft', 'Draft'),
        ('submitted', 'Submitted'),
        ('acknowledged', 'Acknowledged'),
        ('processing', 'Processing'),
        ('completed', 'Completed'),
        ('denied', 'Denied'),
        ('appealed', 'Appealed'),
    ]
    
    # Basic information
    title = models.CharField(max_length=500)
    description = models.TextField()
    status = models.CharField(max_length=20, choices=STATUS_CHOICES, default='draft')
    
    # Relationships
    user = models.ForeignKey(
        settings.AUTH_USER_MODEL,
        on_delete=models.CASCADE,
        related_name='foia_requests'
    )
    agency = models.ForeignKey(
        'agency.Agency',
        on_delete=models.PROTECT,
        related_name='requests'
    )
    
    # Request content
    request_body = models.TextField(
        help_text="The actual FOIA request text"
    )
    
    # Tracking information
    tracking_number = models.CharField(max_length=200, blank=True)
    submitted_date = models.DateTimeField(null=True, blank=True)
    due_date = models.DateField(null=True, blank=True)
    
    # Agent assistance
    agent_assisted = models.BooleanField(
        default=False,
        help_text="Was this request drafted with AI agent assistance?"
    )
    agent_improvements = models.TextField(
        blank=True,
        help_text="Agent suggestions that were applied to this request"
    )
    
    # Response tracking
    response_received = models.BooleanField(default=False)
    response_date = models.DateTimeField(null=True, blank=True)
    response_summary = models.TextField(blank=True)
    
    # Follow-up
    requires_followup = models.BooleanField(default=False)
    followup_notes = models.TextField(blank=True)
    
    class Meta:
        ordering = ['-created_at']
        verbose_name = 'FOIA Request'
        verbose_name_plural = 'FOIA Requests'
    
    def __str__(self):
        return f"{self.title} - {self.get_status_display()}"


class RequestCommunication(TimeStampedModel):
    """
    Tracks communications related to a FOIA request
    """
    DIRECTION_CHOICES = [
        ('outgoing', 'Outgoing'),
        ('incoming', 'Incoming'),
    ]
    
    TYPE_CHOICES = [
        ('email', 'Email'),
        ('letter', 'Letter'),
        ('phone', 'Phone Call'),
        ('portal', 'Portal Message'),
    ]
    
    request = models.ForeignKey(
        FOIARequest,
        on_delete=models.CASCADE,
        related_name='communications'
    )
    direction = models.CharField(max_length=10, choices=DIRECTION_CHOICES)
    communication_type = models.CharField(max_length=20, choices=TYPE_CHOICES)
    subject = models.CharField(max_length=500, blank=True)
    content = models.TextField()
    date = models.DateTimeField(auto_now_add=True)
    
    # Agent assistance
    agent_generated = models.BooleanField(
        default=False,
        help_text="Was this communication generated by an AI agent?"
    )
    
    class Meta:
        ordering = ['-date']
    
    def __str__(self):
        return f"{self.get_direction_display()} - {self.date.strftime('%Y-%m-%d')}"


class RequestDocument(TimeStampedModel):
    """
    Documents attached to or received from FOIA requests
    """
    request = models.ForeignKey(
        FOIARequest,
        on_delete=models.CASCADE,
        related_name='documents'
    )
    title = models.CharField(max_length=500)
    description = models.TextField(blank=True)
    file = models.FileField(upload_to='foia_documents/%Y/%m/')
    file_size = models.BigIntegerField(default=0)
    mime_type = models.CharField(max_length=100, blank=True)
    
    # Classification
    is_request_document = models.BooleanField(
        default=False,
        help_text="Is this document part of the original request?"
    )
    is_response_document = models.BooleanField(
        default=False,
        help_text="Is this document part of an agency response?"
    )
    
    # Agent processing
    agent_processed = models.BooleanField(
        default=False,
        help_text="Has this document been analyzed by an AI agent?"
    )
    agent_summary = models.TextField(
        blank=True,
        help_text="AI-generated summary of the document"
    )
    
    class Meta:
        ordering = ['-created_at']
    
    def __str__(self):
        return self.title
