# Generated by Django 4.2.11 on 2025-11-16 05:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("agency", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="FOIARequest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("is_deleted", models.BooleanField(default=False)),
                ("title", models.CharField(max_length=500)),
                ("description", models.TextField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("submitted", "Submitted"),
                            ("acknowledged", "Acknowledged"),
                            ("processing", "Processing"),
                            ("completed", "Completed"),
                            ("denied", "Denied"),
                            ("appealed", "Appealed"),
                        ],
                        default="draft",
                        max_length=20,
                    ),
                ),
                (
                    "request_body",
                    models.TextField(help_text="The actual FOIA request text"),
                ),
                ("tracking_number", models.CharField(blank=True, max_length=200)),
                ("submitted_date", models.DateTimeField(blank=True, null=True)),
                ("due_date", models.DateField(blank=True, null=True)),
                (
                    "agent_assisted",
                    models.BooleanField(
                        default=False,
                        help_text="Was this request drafted with AI agent assistance?",
                    ),
                ),
                (
                    "agent_improvements",
                    models.TextField(
                        blank=True,
                        help_text="Agent suggestions that were applied to this request",
                    ),
                ),
                ("response_received", models.BooleanField(default=False)),
                ("response_date", models.DateTimeField(blank=True, null=True)),
                ("response_summary", models.TextField(blank=True)),
                ("requires_followup", models.BooleanField(default=False)),
                ("followup_notes", models.TextField(blank=True)),
                (
                    "agency",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="requests",
                        to="agency.agency",
                    ),
                ),
            ],
            options={
                "verbose_name": "FOIA Request",
                "verbose_name_plural": "FOIA Requests",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="RequestDocument",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("title", models.CharField(max_length=500)),
                ("description", models.TextField(blank=True)),
                ("file", models.FileField(upload_to="foia_documents/%Y/%m/")),
                ("file_size", models.BigIntegerField(default=0)),
                ("mime_type", models.CharField(blank=True, max_length=100)),
                (
                    "is_request_document",
                    models.BooleanField(
                        default=False,
                        help_text="Is this document part of the original request?",
                    ),
                ),
                (
                    "is_response_document",
                    models.BooleanField(
                        default=False,
                        help_text="Is this document part of an agency response?",
                    ),
                ),
                (
                    "agent_processed",
                    models.BooleanField(
                        default=False,
                        help_text="Has this document been analyzed by an AI agent?",
                    ),
                ),
                (
                    "agent_summary",
                    models.TextField(
                        blank=True, help_text="AI-generated summary of the document"
                    ),
                ),
                (
                    "request",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="documents",
                        to="requests.foiarequest",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="RequestCommunication",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "direction",
                    models.CharField(
                        choices=[("outgoing", "Outgoing"), ("incoming", "Incoming")],
                        max_length=10,
                    ),
                ),
                (
                    "communication_type",
                    models.CharField(
                        choices=[
                            ("email", "Email"),
                            ("letter", "Letter"),
                            ("phone", "Phone Call"),
                            ("portal", "Portal Message"),
                        ],
                        max_length=20,
                    ),
                ),
                ("subject", models.CharField(blank=True, max_length=500)),
                ("content", models.TextField()),
                ("date", models.DateTimeField(auto_now_add=True)),
                (
                    "agent_generated",
                    models.BooleanField(
                        default=False,
                        help_text="Was this communication generated by an AI agent?",
                    ),
                ),
                (
                    "request",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="communications",
                        to="requests.foiarequest",
                    ),
                ),
            ],
            options={
                "ordering": ["-date"],
            },
        ),
    ]
