# Generated by Django 4.2.11 on 2025-11-16 05:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="AgentSuggestion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("suggestion_type", models.CharField(max_length=50)),
                ("title", models.CharField(max_length=500)),
                ("description", models.TextField()),
                (
                    "suggested_text",
                    models.TextField(blank=True, help_text="Suggested text or content"),
                ),
                ("is_accepted", models.BooleanField(default=False)),
                ("is_rejected", models.BooleanField(default=False)),
                (
                    "feedback",
                    models.TextField(
                        blank=True, help_text="User feedback on the suggestion"
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="AgentTask",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "task_type",
                    models.CharField(
                        choices=[
                            ("draft_request", "Draft FOIA Request"),
                            ("analyze_response", "Analyze Response"),
                            ("generate_followup", "Generate Follow-up"),
                            ("summarize_document", "Summarize Document"),
                            ("suggest_improvements", "Suggest Improvements"),
                            ("prioritize_tasks", "Prioritize Tasks"),
                        ],
                        max_length=30,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("processing", "Processing"),
                            ("completed", "Completed"),
                            ("failed", "Failed"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                (
                    "input_data",
                    models.JSONField(help_text="Input data provided to the agent"),
                ),
                (
                    "output_data",
                    models.JSONField(
                        blank=True, help_text="Output generated by the agent", null=True
                    ),
                ),
                ("started_at", models.DateTimeField(blank=True, null=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                ("error_message", models.TextField(blank=True)),
                (
                    "agent_model",
                    models.CharField(default="gpt-4-turbo-preview", max_length=100),
                ),
                ("tokens_used", models.IntegerField(default=0)),
            ],
            options={
                "verbose_name": "Agent Task",
                "verbose_name_plural": "Agent Tasks",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="AgentWorkflow",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=200)),
                ("description", models.TextField()),
                (
                    "trigger_event",
                    models.CharField(
                        help_text="Event that triggers this workflow (e.g., 'request_submitted')",
                        max_length=50,
                    ),
                ),
                (
                    "actions",
                    models.JSONField(
                        help_text="List of actions the agent should perform"
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("execution_count", models.IntegerField(default=0)),
                ("success_count", models.IntegerField(default=0)),
                ("failure_count", models.IntegerField(default=0)),
            ],
            options={
                "ordering": ["name"],
            },
        ),
    ]
