# Generated by Django 4.2.11 on 2025-11-16 05:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("requests", "0001_initial"),
        ("agents", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="agenttask",
            name="foia_request",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="agent_tasks",
                to="requests.foiarequest",
            ),
        ),
    ]
