# Generated by Django 4.2.11 on 2025-11-16 05:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("agents", "0002_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("requests", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="agenttask",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="agent_tasks",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="agentsuggestion",
            name="foia_request",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="agent_suggestions",
                to="requests.foiarequest",
            ),
        ),
        migrations.AddField(
            model_name="agentsuggestion",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="agent_suggestions",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
